---
- name: Check Disk Space
  hosts: all
  gather_facts: no
  tasks:
    - name: Check disk space
      command: df -h
      register: disk_space

    - name: Show disk space
      debug:
        var: disk_space.stdout_lines
