---
- name: Configure Apache
  hosts: all
  become: yes
  tasks:
    - name: Set server name
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: "CENTOSweb www.centos.com"
        state: present
      notify: Restart Apache Service

    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify: Restart Apache Service
