---
- name: Remove Package on RPM based distro
  hosts: all
  become: yes
  vars:
    - name: package_name

  tasks:
    - name: Remove the package
      package:
        name: "{{ package_name }}"
        state: absent
