---
- name: Gather subset of facts on Virtualization
  hosts: all
  gather_facts: yes

  tasks:
    - name: Display gathered facts
      debug:
        var: 
          - ansible_facts['python_version']
          - ansible_facts['selinux']
          - ansible_facts['virtualization_role']
          - ansible_facts['virtualization_type']
          - ansible_facts['processor']
          - ansible_facts['processor_cores']
          - ansible_facts['processor_count']
          - ansible_facts['iscsi']
          - ansible_facts['ansible_devices']['sda']['size']
